

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cake_site
      POSTGRES_USER: cake_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - ./postgres-dump.sql:/docker-entrypoint-initdb.d/10-dump.sql
    ports:
      - "5432:5432"

  backend:
    build: ./cake_site
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://cake_user:password@db:5432/cake_site
    depends_on:
      - db
    volumes:
      - ./cake_site:/app

  frontend:
    build: ./cake-site-frontend_api
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
